In [3]:
import numpy as np

In [4]:
def sigmoid(z):
    return 1.0/(1.0 + np.exp(-z))

In [9]:
def calculate_gradient(theta, X, y):
    m = y.size #number of instances
    return (X.T @(sigmoid(X @ theta) - y)/m)


In [11]:
def gradient_descent(X, y, alpha = 0.1, num_iter = 100, tol= 1e-7):
    X_b=np.c_[np.ones((X.shape[0], 1)), X]
    
    theta = np.zeros(X_b.shape[1])

    for i in range(num_iter):
        grad = calculate_gradient(theta, X_b, y)
        theta -= alpha * grad

        if np.linalg.norm(grad) < tol:
            break
    return theta

In [7]:
def predict_probs(X, theta):
    x_b = np.c_[np.ones((X.shape[0], 1)), X]
    return sigmoid(x_b @ theta)

In [8]:
def predict(X, theta, threshold = 0.5):
    return(predict_probs(X, theta) >= threshold).astype(int)

In [12]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
y = np.array([0, 0, 1])

theta = gradient_descent(X, y, alpha=0.1, num_iter=1000)
print(theta)                  # learned parameters
print(predict(X, theta))      # predicted classes
print(predict_probs(X, theta))# predicted probabilities


[-5.06603603  3.82608391 -1.23995213]
[0 0 1]
[0.0236639  0.24347439 0.81036862]
